on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: CI Tests & Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - "8.3"
          - "8.4"
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
      - name: Install Dependencies
        run: |
          composer install
      - name: Lint
        continue-on-error: true
        run: |
          composer exec pint
      - name: Test
        run: |
          composer exec phpunit
